spring:
  profiles:
    active: local #default
    group:
      local:
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sns
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true

jwt:
  secret-key: fast_campus.sns-application-2025.secret-key
  # 30 days
  token.expired-time-ms: 2592000

sns:
  service:
    base:
      url: http://localhost:8080/dir/
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://sns-database:3306/sns
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: sns-redis
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate # prod ??? validate
    show-sql: true

sns:
  service:
    base:
      url: http://localhost:8081/dir/
